In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'winequality-red.csv')

In [3]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [5]:
df.duplicated().sum()

240

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df.duplicated().sum()

0

In [8]:
df.tail()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1593            6.8             0.620         0.08             1.9      0.068   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1593                 28.0                  38.0  0.99651  3.42       0.82   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
1593      9.5        6  
1594     10.5        5  
1595     11.2        6  
1597     10.2        5  
1598     11.0        6

In [9]:
df.describe ()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1359.000000       1359.000000  1359.000000     1359.000000   
mean        8.310596          0.529478     0.272333        2.523400   
std         1.736990          0.183031     0.195537        1.352314   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.430000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1359.000000          1359.000000           1359.000000  1359.000000   
mean      0.088124            15.893304             46.825975     0.996709   
std       0.049377            10.447270             33.408946     0.001869   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996700   
75%       0.091000            21.000000             63.000000     0.997820   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1359.000000  1359.000000  1359.000000  1359.000000  
mean      3.309787     0.658705    10.432315     5.623252  
std       0.155036     0.170667     1.082065     0.823578  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [10]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [11]:
df.shape

(1359, 12)

In [12]:
df['quality'].value_counts()

5    577
6    535
7    167
4     53
8     17
3     10
Name: quality, dtype: int64

In [13]:
y=df.quality

In [14]:
y.shape

(1359,)

In [15]:
X = df .drop(['quality'], axis=1)

In [16]:
X.shape

(1359, 11)

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3,random_state=2529)

In [19]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((951, 11), (408, 11), (951,), (408,))

In [20]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
rfc =RandomForestClassifier()

In [22]:
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [23]:
y_pred = rfc.predict(X_test)

In [24]:
y_pred.shape

(408,)

In [25]:
from sklearn.metrics import confusion_matrix, classification_report

In [26]:
print(confusion_matrix(y_test, y_pred))

[[  0   0   1   0   0   0]
 [  0   0  12   2   0   0]
 [  0   0 139  33   1   0]
 [  0   0  52  98  11   1]
 [  0   0   3  30  16   1]
 [  0   0   0   3   5   0]]


In [27]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00        14
           5       0.67      0.80      0.73       173
           6       0.59      0.60      0.60       162
           7       0.48      0.32      0.39        50
           8       0.00      0.00      0.00         8

    accuracy                           0.62       408
   macro avg       0.29      0.29      0.29       408
weighted avg       0.58      0.62      0.59       408



C:\Users\Rahul\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Rahul\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Rahul\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [28]:
import pickle
filename='wine_quality.sav'
pickle.dump(rfc,open(filename,'wb'))
loaded_model=pickle.load(open('wine_quality.sav','rb'))

In [29]:
input_data=(7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4)

#changing the input_data to numpy array
input_data_as_numpy_array=np.asarray(input_data)

#reshape the array as we are predicting for one instance 
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)

prediction=rfc.predict(input_data_reshaped)
print(prediction)

if (prediction[0]==3):
    print("Poor")
elif (prediction[0]==4):
    print('Average')
elif (prediction[0]==5):
    print('Good')
elif (prediction[0]==6):
    print('Fine')
elif (prediction[0]==7):
    print('Superb')
else:
    print("Excellent")

[5]
Good


C:\Users\Rahul\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [30]:
df[df.quality==3]

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
459            11.6             0.580         0.66            2.20      0.074   
517            10.4             0.610         0.49            2.10      0.200   
690             7.4             1.185         0.00            4.25      0.097   
832            10.4             0.440         0.42            1.50      0.145   
899             8.3             1.020         0.02            3.40      0.084   
1299            7.6             1.580         0.00            2.10      0.137   
1374            6.8             0.815         0.00            1.20      0.267   
1469            7.3             0.980         0.05            2.10      0.061   
1478            7.1             0.875         0.05            5.70      0.082   
1505            6.7             0.760         0.02            1.80      0.078   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
459                  10.0                  47.0  1.00080  3.25       0.57   
517                   5.0                  16.0  0.99940  3.16       0.63   
690                   5.0                  14.0  0.99660  3.63       0.54   
832                  34.0                  48.0  0.99832  3.38       0.86   
899                   6.0                  11.0  0.99892  3.48       0.49   
1299                  5.0                   9.0  0.99476  3.50       0.40   
1374                 16.0                  29.0  0.99471  3.32       0.51   
1469                 20.0                  49.0  0.99705  3.31       0.55   
1478                  3.0                  14.0  0.99808  3.40       0.52   
1505                  6.0                  12.0  0.99600  3.55       0.63   

      alcohol  quality  
459      9.00        3  
517      8.40        3  
690     10.70        3  
832      9.90        3  
899     11.00        3  
1299    10.90        3  
1374     9.80        3  
1469     9.70        3  
1478    10.20        3  
1505     9.95        3

In [31]:
df[df.quality==4]

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
18              7.4             0.590         0.08             4.4      0.086   
38              5.7             1.130         0.09             1.5      0.172   
41              8.8             0.610         0.30             2.8      0.088   
45              4.6             0.520         0.15             2.1      0.054   
73              8.3             0.675         0.26             2.1      0.084   
79              8.3             0.625         0.20             1.5      0.080   
94              5.0             1.020         0.04             1.4      0.045   
151             9.2             0.520         1.00             3.4      0.610   
161             7.6             0.680         0.02             1.3      0.072   
167             7.3             0.550         0.03             1.6      0.072   
170             7.9             0.885         0.03             1.8      0.058   
199             6.9             1.090         0.06             2.1      0.061   
224             8.4             0.635         0.36             2.0      0.089   
261             7.0             0.975         0.04             2.0      0.087   
266             8.1             0.870         0.00             3.3      0.096   
409            12.5             0.460         0.49             4.5      0.070   
573            10.5             0.590         0.49             2.1      0.070   
576             9.9             0.500         0.24             2.3      0.103   
600             8.2             0.915         0.27             2.1      0.088   
633            10.1             0.935         0.22             3.4      0.105   
647             8.3             0.845         0.01             2.2      0.070   
659             7.1             0.840         0.02             4.4      0.096   
703             7.5             0.380         0.48             2.6      0.073   
704             9.1             0.765         0.04             1.6      0.078   
724             7.5             1.115         0.10             3.1      0.086   
813             6.9             0.390         0.24             2.1      0.102   
830             7.5             0.685         0.07             2.5      0.058   
833            11.6             0.470         0.44             1.6      0.147   
872             7.3             0.350         0.24             2.0      0.067   
876             7.1             0.470         0.00             2.2      0.067   
927             8.4             0.670         0.19             2.2      0.093   
937            12.0             0.630         0.50             1.4      0.071   
1124            6.5             0.580         0.00             2.2      0.096   
1176            6.5             0.880         0.03             5.6      0.079   
1189            8.8             0.955         0.05             1.8      0.075   
1233           10.2             0.230         0.37             2.2      0.057   
1235            6.0             0.330         0.32            12.9      0.054   
1238            8.1             0.730         0.00             2.5      0.081   
1239            6.5             0.670         0.00             4.3      0.057   
1261            6.3             1.020         0.00             2.0      0.083   
1263            8.2             0.780         0.00             2.2      0.089   
1276            8.5             0.400         0.40             6.3      0.050   
1293            7.5             0.755         0.00             1.9      0.084   
1307            6.8             0.680         0.09             3.9      0.068   
1363            8.0             0.830         0.27             2.0      0.080   
1369            6.6             0.610         0.00             1.6      0.069   
1423            6.4             0.530         0.09             3.9      0.123   
1461            6.2             0.785         0.00             2.1      0.060   
1467            6.7             1.040

In [32]:
df[df.quality==5]

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
5               7.4             0.660         0.00             1.8      0.075   
6               7.9             0.600         0.06             1.6      0.069   
...             ...               ...          ...             ...        ...   
1582            6.1             0.715         0.10             2.6      0.053   
1583            6.2             0.460         0.29             2.1      0.074   
1589            6.6             0.725         0.20             7.8      0.073   
1594            6.2             0.600         0.08             2.0      0.090   
1597            5.9             0.645         0.12             2.0      0.075   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
5                    13.0                  40.0  0.99780  3.51       0.56   
6                    15.0                  59.0  0.99640  3.30       0.46   
...                   ...                   ...      ...   ...        ...   
1582                 13.0                  27.0  0.99362  3.57       0.50   
1583                 32.0                  98.0  0.99578  3.33       0.62   
1589                 29.0                  79.0  0.99770  3.29       0.54   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1597                 32.0                  44.0  0.99547  3.57       0.71   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
5         9.4        5  
6         9.4        5  
...       ...      ...  
1582     11.9        5  
1583      9.8        5  
1589      9.2        5  
1594     10.5        5  
1597     10.2        5  

[577 rows x 12 columns]

In [33]:
df[df.quality==6]

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
3              11.2             0.280         0.56             1.9      0.075   
19              7.9             0.320         0.51             1.8      0.341   
20              8.9             0.220         0.48             1.8      0.077   
24              6.9             0.400         0.14             2.4      0.085   
29              7.8             0.645         0.00             2.0      0.082   
...             ...               ...          ...             ...        ...   
1591            5.4             0.740         0.09             1.7      0.089   
1592            6.3             0.510         0.13             2.3      0.076   
1593            6.8             0.620         0.08             1.9      0.068   
1595            5.9             0.550         0.10             2.2      0.062   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
3                    17.0                  60.0  0.99800  3.16       0.58   
19                   17.0                  56.0  0.99690  3.04       1.08   
20                   29.0                  60.0  0.99680  3.39       0.53   
24                   21.0                  40.0  0.99680  3.43       0.63   
29                    8.0                  16.0  0.99640  3.38       0.59   
...                   ...                   ...      ...   ...        ...   
1591                 16.0                  26.0  0.99402  3.67       0.56   
1592                 29.0                  40.0  0.99574  3.42       0.75   
1593                 28.0                  38.0  0.99651  3.42       0.82   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
3         9.8        6  
19        9.2        6  
20        9.4        6  
24        9.7        6  
29        9.8        6  
...       ...      ...  
1591     11.6        6  
1592     11.0        6  
1593      9.5        6  
1595     11.2        6  
1598     11.0        6  

[535 rows x 12 columns]

In [34]:
df[df.quality==7]

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
7               7.3              0.65         0.00             1.2      0.065   
8               7.8              0.58         0.02             2.0      0.073   
16              8.5              0.28         0.56             1.8      0.092   
37              8.1              0.38         0.28             2.1      0.066   
62              7.5              0.52         0.16             1.9      0.085   
...             ...               ...          ...             ...        ...   
1534            6.6              0.56         0.14             2.4      0.064   
1541            7.4              0.25         0.29             2.2      0.054   
1544            8.4              0.37         0.43             2.3      0.063   
1555            7.0              0.56         0.17             1.7      0.065   
1584            6.7              0.32         0.44             2.4      0.061   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
7                    15.0                  21.0  0.99460  3.39       0.47   
8                     9.0                  18.0  0.99680  3.36       0.57   
16                   35.0                 103.0  0.99690  3.30       0.75   
37                   13.0                  30.0  0.99680  3.23       0.73   
62                   12.0                  35.0  0.99680  3.38       0.62   
...                   ...                   ...      ...   ...        ...   
1534                 13.0                  29.0  0.99397  3.42       0.62   
1541                 19.0                  49.0  0.99666  3.40       0.76   
1544                 12.0                  19.0  0.99550  3.17       0.81   
1555                 15.0                  24.0  0.99514  3.44       0.68   
1584                 24.0                  34.0  0.99484  3.29       0.80   

      alcohol  quality  
7       10.00        7  
8        9.50        7  
16      10.50        7  
37       9.70        7  
62       9.50        7  
...       ...      ...  
1534    11.70        7  
1541    10.90        7  
1544    11.20        7  
1555    10.55        7  
1584    11.60        7  

[167 rows x 12 columns]

In [35]:
df[df.quality==8]

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
267             7.9              0.35         0.46             3.6      0.078   
278            10.3              0.32         0.45             6.4      0.073   
390             5.6              0.85         0.05             1.4      0.045   
440            12.6              0.31         0.72             2.2      0.072   
455            11.3              0.62         0.67             5.2      0.086   
481             9.4              0.30         0.56             2.8      0.080   
495            10.7              0.35         0.53             2.6      0.070   
588             5.0              0.42         0.24             2.0      0.060   
828             7.8              0.57         0.09             2.3      0.065   
1061            9.1              0.40         0.50             1.8      0.071   
1090           10.0              0.26         0.54             1.9      0.083   
1120            7.9              0.54         0.34             2.5      0.076   
1202            8.6              0.42         0.39             1.8      0.068   
1269            5.5              0.49         0.03             1.8      0.044   
1403            7.2              0.33         0.33             1.7      0.061   
1449            7.2              0.38         0.31             2.0      0.056   
1549            7.4              0.36         0.30             1.8      0.074   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
267                  15.0                  37.0  0.99730  3.35       0.86   
278                   5.0                  13.0  0.99760  3.23       0.82   
390                  12.0                  88.0  0.99240  3.56       0.82   
440                   6.0                  29.0  0.99870  2.88       0.82   
455                   6.0                  19.0  0.99880  3.22       0.69   
481                   6.0                  17.0  0.99640  3.15       0.92   
495                   5.0                  16.0  0.99720  3.15       0.65   
588                  19.0                  50.0  0.99170  3.72       0.74   
828                  34.0                  45.0  0.99417  3.46       0.74   
1061                  7.0                  16.0  0.99462  3.21       0.69   
1090                 42.0                  74.0  0.99451  2.98       0.63   
1120                  8.0                  17.0  0.99235  3.20       0.72   
1202                  6.0                  12.0  0.99516  3.35       0.69   
1269                 28.0                  87.0  0.99080  3.50       0.82   
1403                  3.0                  13.0  0.99600  3.23       1.10   
1449                 15.0                  29.0  0.99472  3.23       0.76   
1549                 17.0                  24.0  0.99419  3.24       0.70   

      alcohol  quality  
267      12.8        8  
278      12.6        8  
390      12.9        8  
440       9.8        8  
455      13.4        8  
481      11.7        8  
495      11.0        8  
588      14.0        8  
828      12.7        8  
1061     12.5        8  
1090     11.8        8  
1120     13.1        8  
1202     11.7        8  
1269     14.0        8  
1403     10.0        8  
1449     11.3        8  
1549     11.4        8